export const ScreenNames = {
  LoginScreen: "LoginScreen",
  SplashScreen: "SplashScreen",
  HomeScreen: "HomeScreen",
  Drawer: "Drawer",
  Base: "Base",
  ScanScreen: "ScanScreen",
  RideInstructionsScreen: "RideInstructionsScreen",
  RideScreen: "RideScreen",
  Registration: "RegistrationScreen",
  ConfirmOtp: "ConfirmOtpScreen",
  PersonalInformation: "PersonalInformationScreen",
  BalanceScreen: "BalanceScreen",
  TopUpScreen: "TopUpScreen",
  HowToRideScreen: "HowToRideScreen",
  PaymentOptionsScreen: "PaymentOptionsScreen",
  RideHistoryScreen: "RideHistoryScreen",
  AddCardScreen: "AddCardScreen",
  ThreeDsAuthWebviewScreen: "ThreeDsAuthWebviewScreen",
  PaymentGatewayScreen: "PaymentGatewayScreen",
  ViewProfileScreen: "ViewProfileScreen",
  HomeStack: "HomeStack",
};
